// AUTH
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGOUT = "LOGOUT";

// EQUIPMENT
export const ADD_EQUIPMENT_REQUEST = "ADD_EQUIPMENT_REQUEST";
export const ADD_EQUIPMENT_SUCCESS = "ADD_EQUIPMENT_SUCCESS";
export const ADD_EQUIPMENT_FAILURE = "ADD_EQUIPMENT_FAILURE";

export const EDIT_EQUIPMENT_REQUEST = "EDIT_EQUIPMENT_REQUEST";
export const EDIT_EQUIPMENT_SUCCESS = "EDIT_EQUIPMENT_SUCCESS";
export const EDIT_EQUIPMENT_FAILURE = "EDIT_EQUIPMENT_FAILURE";

export const DELETE_EQUIPMENT_REQUEST = "DELETE_EQUIPMENT_REQUEST";
export const DELETE_EQUIPMENT_SUCCESS = "DELETE_EQUIPMENT_SUCCESS";
export const DELETE_EQUIPMENT_FAILURE = "DELETE_EQUIPMENT_FAILURE";

export const LIST_EQUIPMENT_REQUEST = "LIST_EQUIPMENT_REQUEST";
export const LIST_EQUIPMENT_SUCCESS = "LIST_EQUIPMENT_SUCCESS";
export const LIST_EQUIPMENT_FAILURE = "LIST_EQUIPMENT_FAILURE";

// REQUEST
export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_REQUEST_SUCCESS = "CREATE_REQUEST_SUCCESS";
export const CREATE_REQUEST_FAILURE = "CREATE_REQUEST_FAILURE";

export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAILURE = "FETCH_REQUESTS_FAILURE";

export const UPDATE_REQUEST_STATUS = "UPDATE_REQUEST_STATUS";
export const UPDATE_REQUEST_STATUS_SUCCESS = "UPDATE_REQUEST_STATUS_SUCCESS";
export const UPDATE_REQUEST_STATUS_FAILURE = "UPDATE_REQUEST_STATUS_FAILURE";

export const RETURN_REQUEST = "RETURN_REQUEST";
export const RETURN_REQUEST_SUCCESS = "RETURN_REQUEST_SUCCESS";
export const RETURN_REQUEST_FAILURE = "RETURN_REQUEST_FAILURE";

// ANALYTICS
export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE";

export const FETCH_SUMMARY = "FETCH_SUMMARY";
export const FETCH_SUMMARY_SUCCESS = "FETCH_SUMMARY_SUCCESS";
export const FETCH_SUMMARY_FAILURE = "FETCH_SUMMARY_FAILURE";
